DROP DATABASE IF EXISTS AUTH;

CREATE DATABASE IF NOT EXISTS AUTH;
USE AUTH;

CREATE TABLE IF NOT EXISTS USERS
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSIONS
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT          NOT NULL,
    TOKEN   VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PERMISSIONS
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CUSTOMERS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      INT          NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    ADDRESS      VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS
(
    ROLE_ID       INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID)
);


INSERT INTO ROLES (NAME)
VALUES ('ADMIN');
INSERT INTO ROLES (NAME)
VALUES ('USER');

INSERT INTO PERMISSIONS (NAME)
VALUES ('READ');
INSERT INTO PERMISSIONS (NAME)
VALUES ('WRITE');

INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('admin', 'admin');
INSERT INTO USERS (USERNAME, PASSWORD)
VALUES ('user', 'user123');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (2, 2);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
VALUES (1, 1);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
VALUES (1, 2);
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
VALUES (2, 1);

INSERT INTO CUSTOMERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS)
VALUES (1, 'John', 'Doe', 'john.doe@gmail.com', '1234567890', '123 Main St');
INSERT INTO CUSTOMERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS)
VALUES (2, 'Lisa', 'Smith', 'lisa.smith@gmail.com', '0987654321', '456 Elm St');

